export * from "./achievement.model";
export * from "./appointment.model";
export * from "./availability.model";
export * from "./chatRoom.model";
export * from "./comment.model";
export * from "./lawyer.model";
export * from "./message.model";
export * from "./notfication.model";
export * from "./post.model";
export * from "./review.model";
export * from "./specialization.model";
export * from "./document.model";
export * from "./lawyer-specialization.model"